Updated dry-wit

diff --git a/.templates/common-files/dry-wit b/.templates/common-files/dry-wit
--- a/.templates/common-files/dry-wit
+++ b/.templates/common-files/dry-wit
@@ -523,19 +523,26 @@ function defineEnvVar() {
   fi
 
   if isNotEmpty "${_varDefault}"; then
-      _addEnvVarDefault "${_upcasedVarName}" "${_varDefault}";
-      if _evalVarDefault "${_upcasedVarName}"; then
-          _defaultValue="${RESULT}";
+    _addEnvVarDefault "${_upcasedVarName}" "${_varDefault}";
+    if _evalVarDefault "${_upcasedVarName}"; then
+      _defaultValue="${RESULT}";
 
-          if isNotEmpty "${_defaultValue}"; then
-              _varValue="${_defaultValue}";
-          elif isNotEmpty "${_varCommand}"; then
-              _addEnvVarCommand "${_upcasedVarName}" "${_varCommand}";
-              if _evalVarCommand "${_upcasedVarName}"; then
-                  _varValue="${RESULT}";
-              fi
+      _evalVar "${_upcasedVarName}";
+      _varValue="${RESULT}";
+
+      if isEmpty "${_varValue}"; then
+        if isNotEmpty "${_defaultValue}"; then
+          _varValue="${_defaultValue}";
+        elif isNotEmpty "${_varCommand}"; then
+          _addEnvVarCommand "${_upcasedVarName}" "${_varCommand}";
+          if _evalVarCommand "${_upcasedVarName}"; then
+            _varValue="${RESULT}";
           fi
+        fi
+      else
+        appendEnvVariable "${_upcasedVarName}";
       fi
+    fi
   fi
 
   if isNotEmpty "${_varValue}"; then
@@ -549,20 +556,23 @@ function defineEnvVar() {
 # Overrides the value of an environment variable.
 # -> 1: The variable name.
 # -> 2: The variable value.
+# -> 3: The variable description (optional).
 function overrideEnvVar() {
   local _varName="${1}";
   local _varValue="${2}";
+  local _varDescription="${3:-not provided}";
   local _upcasedVarName;
 
   checkNotEmpty "varName" "${_varName}" 1;
 
-  toUpper "${_varName}";
-  _upcasedVarName="${RESULT}";
-  _addOverriddenEnvVar "${_upcasedVarName}" "${_varValue}";
-
-  if isNotEmpty "${_varValue}"; then
-      _addEnvVar "${_upcasedVarName}" "${_varValue}";
+  if isEnvVarDefined ${_varName}; then
+    toUpper "${_varName}";
+    _upcasedVarName="${RESULT}";
+    _addOverriddenEnvVar "${_upcasedVarName}" "${_varValue}";
   fi
+  defineEnvVar "${_varName}" "${_varDescription}" "${_varValue}";
+
+  return ${TRUE};
 }
 
 ## PUBLIC
@@ -782,7 +792,7 @@ function _evalEnvVar() {
     fi
 
     if isNotEmpty "${_varValue}"; then
-        export ${_varName}="${_varValue}";
+        export ${_varName}="${_varValue}" 2> /dev/null;
         export RESULT="${_varValue}";
         rescode=${TRUE};
     else
@@ -997,9 +1007,9 @@ function flagEnabled() {
     rescode=${TRUE};
   else
     rescode=${FALSE};
-fi
+  fi
 
-  return ${result};
+  return ${rescode};
 }
 
 # AUXILIARY GENERAL-PURPOSE FUNCTIONS
@@ -2088,7 +2098,7 @@ buildColor "GRAY" "37" "47";
 export SUCCESS_COLOR=GREEN;
 export FAILURE_COLOR=RED;
 export IN_PROGRESS_COLOR=BLUE;
-export UNDEFINED_COLOR=GREY;
+export UNDEFINED_COLOR=GRAY;
 export DEFAULT_LOG_PREFIX_COLOR=GRAY;
 export DEFAULT_LOG_OUTCOME_COLOR=GRAY;
 export DEFAULT_LOG_RESUMING_TASK_COLOR=GRAY;
@@ -2096,10 +2106,10 @@ export DEFAULT_LOG_RESUMING_TASK_COLOR=GRAY;
 export LOG_PREFIX_COLORS=(\
   BLUE   \
   CYAN  \
-  RED    \
+  YELLOW \
+  MAGENTA    \
   YELLOW \
   RED \
-  GRAY \
   BLUE   \
 );
 
@@ -4175,6 +4185,25 @@ function checkDependency() {
   fi
 }
 
+## Checks a required dependency is installed.
+## -> 1: The program name.
+## <- 0/${TRUE} if given program is available in the PATH; 1/${FALSE} otherwise.
+## Example:
+##   if ! isInstalled "ifconfig"; then
+##     echo "ifconfig is not available";
+##   fi
+function isInstalled() {
+  local _req="${1}";
+  local -i _rescode;
+
+  checkNotEmpty "candidate" "{_req}" 1;
+
+  which ${_req} > /dev/null 2>&1;
+  _rescode=$?;
+
+  return ${_rescode};
+}
+
 ## Performs the checks for a required dependency.
 ## -> 1: The dependency.
 function checkReq() {
@@ -4839,12 +4868,12 @@ function _checkScript() {
 ##   sourceFileIfExists "/tmp/my-env";
 function sourceFileIfExists() {
   local _file="${1}";
-  local rescode=${FALSE};
+  local -i rescode=${FALSE};
 
   checkNotEmpty "file" "${_file}" 1;
 
   logTrace -n "Reading ${_file}";
-  if [ -e "${_file}" ]; then
+  if fileExists "${_file}"; then
     rescode=${TRUE};
     source "${_file}";
     logTraceResult SUCCESS "done";
@@ -4856,20 +4885,36 @@ function sourceFileIfExists() {
 }
 
 ## PRIVATE
-## Retrieves the settings files
+## Retrieves the settings files.
+## <- RESULT: a space-separated list of settings files.
+## Example:
+##   _retrieveSettingsFiles;
+##   echo "settings files: ${RESULT}";
 function _retrieveSettingsFiles() {
-  echo 1;
+  local _f;
+  local _d;
+  local _result="";
+  local _oldIFS="${IFS}";
+  IFS=$' \t\n';
+  for _f in "$(basename ${DRY_WIT_SCRIPT_PATH} .sh).inc.sh" ".$(basename ${DRY_WIT_SCRIPT_PATH} .sh).inc.sh"; do
+    for _d in "${DRY_WIT_SCRIPT_FOLDER}" "."; do
+      _result="${_result} ${_d}/${_f}";
+    done
+  done
+  IFS="${_oldIFS}";
+
+  export RESULT="${_result}";
 }
 
 function _setup() {
   _trapSignals;
   local _f;
+  _retrieveSettingsFiles;
+  local _files="${RESULT}"
   local _oldIFS="${IFS}";
   IFS=$' \t\n';
-  for _f in "${DRY_WIT_SCRIPT_FOLDER}/$(basename ${DRY_WIT_SCRIPT_PATH} .sh).inc.sh" \
-            "./.$(basename ${DRY_WIT_SCRIPT_PATH} .sh).inc.sh" \
-            "${DRY_WIT_SCRIPT_FOLDER}/.$(basename ${DRY_WIT_SCRIPT_PATH} .sh).inc.sh" \
-            "./.$(basename ${DRY_WIT_SCRIPT_PATH} .sh).inc.sh"; do
+
+  for _f in ${_files}; do
     sourceFileIfExists "${_f}";
   done
   IFS="${_oldIFS}";
@@ -4990,14 +5035,26 @@ function retrieveIfaces() {
   local _result;
   local -i _rescode;
 
-  logTrace -n "Finding out the names of the network interfaces";
-  _result="$(ifconfig | cut -d' ' -f1 | grep -v -e '^$' | tr ' ' '\n' | tr -d ':' | grep -v -e '^docker' | grep -v -e '^lo$' | grep -v -e '^tun' | grep -v -e '^vbox' | grep -v -e '^veth' | grep -v -e '^br-')";
-  _rescode=$?;
-  if isTrue ${_rescode}; then
+  if isInstalled "ip"; then
+    logTrace -n "Finding out the names of the network interfaces";
+    _result="$(ip addr show 2> /dev/null | awk '/inet.*brd/{print $NF}'  | grep -v -e '^docker' | grep -v -e '^lo$' | grep -v -e '^tun' | grep -v -e '^vbox' | grep -v -e '^veth' | grep -v -e '^br-')";
+    _rescode=$?;
+    if isTrue ${_rescode}; then
       logTraceResult SUCCESS "$(echo ${_result})";
       export RESULT="${_result}";
-  else
-    logTraceResult FAILED "failed";
+    else
+      logTraceResult FAILED "failed";
+    fi
+  elif isInstalled "ifconfig"; then
+    logTrace -n "Finding out the names of the network interfaces";
+    _result="$(ifconfig 2> /dev/null | cut -d' ' -f1 | grep -v -e '^$' | tr ' ' '\n' | tr -d ':' | grep -v -e '^docker' | grep -v -e '^lo$' | grep -v -e '^tun' | grep -v -e '^vbox' | grep -v -e '^veth' | grep -v -e '^br-')";
+    _rescode=$?;
+    if isTrue ${_rescode}; then
+      logTraceResult SUCCESS "$(echo ${_result})";
+      export RESULT="${_result}";
+    else
+      logTraceResult FAILED "failed";
+    fi
   fi
 
   return ${_rescode};
@@ -5014,12 +5071,12 @@ function retrieveIface() {
   local -i _rescode=${FALSE};
 
   if retrieveIfaces; then
-      echo "${RESULT}" | awk -F' ' '{print $1;}';
-      _rescode=$?;
+    _result="$(echo "${RESULT}" | awk -F' ' '{print $1;}')";
+    _rescode=$?;
   fi
 
   if isTrue ${_rescode}; then
-      export RESULT="${_result}";
+    export RESULT="${_result}";
   else
     export RESULT="";
   fi
@@ -5042,11 +5099,19 @@ function retrieveIp() {
 
   checkNotEmpty "interface" "${_iface}" 1;
 
-  _result="$(ifconfig ${_iface} | grep 'inet ' | sed 's/ addr:/:/g' | sed 's/inet /inet:/g' | cut -d':' -f 2 | awk '{print $1;}')";
-  _rescode=$?;
+  if isInstalled "ifconfig"; then
+    _result="$(ifconfig ${_iface} 2> /dev/null | grep 'inet ' | sed 's/ addr:/:/g' | sed 's/inet /inet:/g' | cut -d':' -f 2 | awk '{print $1;}')";
+    _rescode=$?;
+  elif isInstalled "ip"; then
+    _result="$(ip -4 -o addr show dev ${_iface} 2> /dev/null | awk '{split($4,a,"/");print a[1]}')";
+    _rescode=$?;
+  else
+    _rescode=${FALSE};
+    export RESULT="Neither ifconfig nor ip are available";
+  fi
 
   if isTrue ${_rescode}; then
-      export RESULT=${_result};
+    export RESULT=${_result};
   fi
 
   return ${_rescode};
@@ -5063,6 +5128,8 @@ function retrieveOwnIp() {
   local -i _rescode;
   local _result;
   local _oldIFS="${IFS}";
+  local _iface;
+  local _ifaces;
   IFS=$' \t\n';
 
   if retrieveIfaces; then
@@ -5223,7 +5290,7 @@ function copyToDockerContainer() {
       export RESULT="${_output}";
   fi
 
-  return ${_restode};
+  return ${_rescode};
 }
 
 ## Runs a Docker command.
